import React from 'react';
import type {HealthResponse,JobListResponse} from '../../api/types';
import type {NavTab} from '../layout/Sidebar';
import {ArrowRight,Search,Hammer,Sparkles,Gauge,Box,Check,Clock3} from 'lucide-react';
import dashboardHeroImg from '../../assets/visuals/dashboard_hero.jpg';
interface Props{health:HealthResponse|null;jobsList:JobListResponse|null;isLoadingJobs:boolean;onNavigate:(tab:NavTab)=>void;onSelectJob:(jobId:string)=>void}
const JOURNEY=[{label:'Model',sub:'Discover',icon:Search,tab:'explorer' as NavTab},{label:'Prepare',sub:'Resolve',icon:Sparkles,tab:'engineer' as NavTab},{label:'Build',sub:'Package',icon:Hammer,tab:'forge' as NavTab},{label:'Optimize',sub:'Compare',icon:Gauge,tab:'optimization' as NavTab},{label:'Validate',sub:'Prove',icon:Check,tab:'optimization' as NavTab}];
const typeLabel:Record<string,string>={FORGE_BUILD:'Forge build',ENGINEER:'Engineer session',OPTIMIZATION:'Optimization study'};
export const DashboardView:React.FC<Props>=({health,jobsList,isLoadingJobs,onNavigate,onSelectJob})=>{const jobs=jobsList?.items||[];return <div className="page-fade">
  <section className="relative min-h-[540px] overflow-hidden border-b hairline flex items-center">
    <img src={dashboardHeroImg} alt="Compute infrastructure" className="hero-image absolute inset-y-0 right-0 w-[67%] h-full object-cover opacity-70"/>
    <div className="absolute inset-0 bg-gradient-to-r from-[#09090b] via-[#09090b]/90 to-transparent"/><div className="absolute inset-0 grid-glow opacity-30"/>
    <div className="relative page-shell py-20"><div className="max-w-[760px]"><div className="eyebrow mb-6">Open model infrastructure for AMD</div><h1 className="display-title max-w-[720px]">From model to<br/><span className="text-zinc-500">production artifact.</span></h1><p className="lede max-w-xl mt-7">Inspect, prepare, package, and evaluate AI models for AMD hardware in one truthful, reproducible workflow.</p><div className="flex flex-wrap gap-3 mt-9"><button onClick={()=>onNavigate('explorer')} className="btn-primary">Explore a model <ArrowRight size={16}/></button><button onClick={()=>onNavigate('forge')} className="btn-secondary"><Hammer size={15}/>Open Forge</button></div><div className="mt-7 flex items-center gap-2 text-xs text-zinc-500"><span className={`w-2 h-2 rounded-full ${health?.rocm_available?'bg-emerald-400':'bg-amber-400'}`}/>{health?.rocm_available?'Hardware acceleration available':'Build planning ready · Hardware measurement on a ROCm host'}</div></div></div>
  </section>
  <section className="page-shell py-16"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-6 mb-10"><div><div className="eyebrow mb-3">One continuous workflow</div><h2 className="text-3xl md:text-4xl font-semibold tracking-[-.04em]">Move with confidence at every stage.</h2></div><p className="text-sm text-zinc-500 max-w-md leading-relaxed">Each handoff preserves model context while technical evidence stays available when you need it.</p></div>
    <div className="grid grid-cols-1 sm:grid-cols-5 gap-2">{JOURNEY.map((s,i)=>{const Icon=s.icon;return <button key={s.label} onClick={()=>onNavigate(s.tab)} className="group relative text-left p-5 min-h-[160px] rounded-2xl bg-white/[.025] border hairline hover:bg-white/[.06] hover:border-white/20 transition-all"><div className="text-[10px] text-zinc-600 font-mono">0{i+1}</div><Icon size={21} className="mt-7 text-zinc-500 group-hover:text-red-400 transition-colors"/><div className="mt-4 font-semibold">{s.label}</div><div className="text-xs text-zinc-600 mt-1">{s.sub}</div>{i<4&&<ArrowRight size={14} className="hidden sm:block absolute -right-[9px] top-1/2 text-zinc-700 z-10"/>}</button>})}</div>
  </section>
  <section className="page-shell pt-0 pb-20"><div className="flex items-center justify-between mb-6"><div><div className="eyebrow mb-2">Workspace</div><h2 className="text-2xl font-semibold tracking-[-.03em]">{jobs.length?'Continue where you left off':'Your first artifact starts here'}</h2></div>{jobs.length>0&&<span className="text-xs text-zinc-600">{jobs.length} recent</span>}</div>
    {isLoadingJobs?<div className="h-40 rounded-2xl shimmer"/>:jobs.length===0?<div className="focus-panel p-8 md:p-11 flex flex-col md:flex-row md:items-center justify-between gap-8"><div className="flex gap-5"><div className="w-12 h-12 shrink-0 rounded-xl bg-red-500/10 flex items-center justify-center text-red-400"><Box size={22}/></div><div><h3 className="text-lg font-semibold">Prepare an open model for AMD</h3><p className="text-sm text-zinc-500 mt-2 max-w-xl leading-relaxed">Begin with model inspection. ROCmHub will resolve its architecture and revision, then carry that context into a reproducible build.</p></div></div><button onClick={()=>onNavigate('explorer')} className="btn-primary shrink-0">Choose a model <ArrowRight size={15}/></button></div>:<div className="grid lg:grid-cols-3 gap-3">{jobs.slice(0,6).map(job=><button key={job.job_id} onClick={()=>onSelectJob(job.job_id)} className="card-interactive p-5 text-left"><div className="flex justify-between gap-4"><span className="text-xs text-zinc-500">{typeLabel[job.job_type]||job.job_type}</span><span className={`w-2 h-2 mt-1 rounded-full ${job.status==='SUCCEEDED'?'bg-emerald-400':job.status==='FAILED'?'bg-red-400':'bg-amber-400'}`}/></div><div className="mt-5 font-semibold truncate">{job.model_id.split('/').pop()}</div><div className="text-xs text-zinc-600 mt-1 truncate">{job.model_id}</div><div className="mt-5 pt-4 border-t hairline flex items-center justify-between text-[11px] text-zinc-500"><span className="flex gap-1.5 items-center"><Clock3 size={12}/>{new Date(job.created_at).toLocaleDateString()}</span><span>{job.domain_status==='CONFIG_ONLY'?'Plan ready':job.status.toLowerCase()}</span></div></button>)}</div>}
  </section>
</div>};
