import React,{useEffect,useState} from 'react';
import type {JobEvent,JobResultResponse,JobStatus,ModelMetadata} from '../../api/types';
import {fetchModel,createJob,fetchJob,fetchJobResult,cancelJob,ApiError} from '../../api/client';
import {subscribeToJobEvents} from '../../api/sse';
import {Search,ArrowRight,Layers,Box,CheckCircle2,AlertTriangle,ChevronDown,RotateCcw,Download,Square,ShieldCheck} from 'lucide-react';
import type {NavTab} from '../layout/Sidebar';
import {useToast} from '../common/Toast';
import {DOMAIN_STATUS_COPY,jobProgressCopy,materializationCopy} from '../../ui/presentation';
interface Props{onSelectModelForForge:(modelId:string,revision?:string)=>void;onNavigate:(tab:NavTab)=>void;selectedJobId?:string|null;initialModelId?:string}
const PRESETS=[{id:'Qwen/Qwen2.5-0.5B-Instruct',name:'Qwen 2.5',size:'0.5B',note:'Compact instruction model'},{id:'Qwen/Qwen2.5-1.5B-Instruct',name:'Qwen 2.5',size:'1.5B',note:'Small instruction model'},{id:'Qwen/Qwen2.5-7B-Instruct',name:'Qwen 2.5',size:'7B',note:'Larger instruction model'}];
const JOB_STORAGE_KEY='rocmhub.model-explorer.active-job';
export const ModelExplorerView:React.FC<Props>=({onSelectModelForForge,onNavigate,selectedJobId,initialModelId})=>{const toast=useToast();const[modelId,setModelId]=useState(initialModelId||PRESETS[0].id);const[revision,setRevision]=useState('main');const[metadata,setMetadata]=useState<ModelMetadata|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const[preparing,setPreparing]=useState(false);const[consentOpen,setConsentOpen]=useState(false);const[consent,setConsent]=useState(false);const[jobId,setJobId]=useState<string|null>(()=>{try{return selectedJobId||sessionStorage.getItem(JOB_STORAGE_KEY)}catch{return selectedJobId||null}});const[jobEvents,setJobEvents]=useState<JobEvent[]>([]);const[jobResult,setJobResult]=useState<JobResultResponse|null>(null);const[jobStatus,setJobStatus]=useState<JobStatus|null>(null);const[jobError,setJobError]=useState<string|null>(null);const[subscriptionKey,setSubscriptionKey]=useState(0);const[workspaceTab,setWorkspaceTab]=useState<'overview'|'runs'|'files'|'compatibility'>('overview');
void onNavigate;
useEffect(()=>{if(selectedJobId){setJobId(selectedJobId);try{sessionStorage.setItem(JOB_STORAGE_KEY,selectedJobId)}catch{}}},[selectedJobId]);
const[lastWasFull,setLastWasFull]=useState(false);
const updateModel=(value:string)=>{setModelId(value);setMetadata(null);setError(null)};
const inspect=async(e?:React.FormEvent)=>{e?.preventDefault();if(!modelId.trim())return;setLoading(true);setError(null);try{setMetadata(await fetchModel(modelId.trim(),revision.trim()||'main'));toast.success('Model inspection complete')}catch(err:any){const msg=err instanceof ApiError?err.message:err.message||'Unable to inspect model';setError(msg);setMetadata(null);toast.error(msg)}finally{setLoading(false)}};
useEffect(()=>{if(initialModelId?.trim()){setModelId(initialModelId);setLoading(true);setError(null);void fetchModel(initialModelId.trim(),'main').then(setMetadata).catch((err:any)=>setError(err.message||'Unable to inspect model')).finally(()=>setLoading(false))}},[initialModelId]);
const startPreparation=async(full:boolean)=>{if(!metadata)return;if(full&&!consent){setConsentOpen(true);return}setLastWasFull(full);setPreparing(true);setJobError(null);setJobResult(null);setJobEvents([]);try{const job=await createJob({job_type:'PREPARE_MODEL_FOR_AMD',model_id:metadata.model_id,revision:metadata.commit_sha,target_gpu:'Radeon RX 7900 XTX',target_gfx:'gfx1100',precision:'fp16',runtime:'pytorch_transformers_hip',allow_full_weights:false,materialization_mode:full?'FULL_WEIGHTS':'METADATA_ONLY',weights_consent:full,expected_capabilities:['PREPARE_MODEL_FOR_AMD'],cache_policy:'REUSE'});setJobStatus(job.status);try{sessionStorage.setItem(JOB_STORAGE_KEY,job.job_id)}catch{}setJobId(job.job_id);toast.success(full?'Download & Prepare queued':'Setup preparation queued')}catch(err:any){const msg=err.message||'Unable to queue preparation';setJobError(msg);toast.error(msg)}finally{setPreparing(false)}};
useEffect(()=>{if(!jobId)return;let dead=false;let unsubscribe:(()=>void)|null=null;const done=async()=>{try{const job=await fetchJob(jobId);if(dead)return;if(!['SUCCEEDED','FAILED','CANCELLED'].includes(job.status))return;const result=await fetchJobResult(jobId);if(!dead){setJobResult(result);try{sessionStorage.removeItem(JOB_STORAGE_KEY)}catch{}setJobError(result.job_status==='FAILED'?result.error_message||'Preparation failed':null)}}catch(e:any){if(!dead)setJobError(e.message||'Could not load preparation result')}};const resume=async()=>{try{const job=await fetchJob(jobId);if(dead)return;setModelId(job.model_id);void fetchModel(job.model_id,job.revision||'main').then(value=>{if(!dead)setMetadata(value)}).catch(()=>{});if(['SUCCEEDED','FAILED','CANCELLED'].includes(job.status)){await done();return}unsubscribe=subscribeToJobEvents(jobId,{onEvent:e=>{if(!dead)setJobEvents(items=>[...items,e])},onComplete:done,onError:()=>{if(!dead){setJobError('Live updates are paused. The same job is being checked directly.');toast.warning('Live updates are interrupted. Checking the same preparation job directly.')}},onDegraded:degraded=>{if(!dead&&!degraded)setJobError(value=>value?.startsWith('Live updates are paused.')?null:value)}})}catch(e:any){if(!dead)setJobError(e.message||'Could not reconnect to preparation')}};void resume();return()=>{dead=true;unsubscribe?.()}},[jobId,subscriptionKey]);
const estimateBytes=metadata?.parameter_count?Math.ceil(metadata.parameter_count*2*1.2):null;
const latestEvent=jobEvents.at(-1);
const currentProgress=(latestEvent?.status as JobStatus|undefined)??jobStatus??'QUEUED';
const cacheStatus=jobResult?.result?.materialization?.cache_status||jobEvents.find(event=>event.details?.materialization?.cache_status)?.details?.materialization?.cache_status||null;
const cachedFiles=cacheStatus==='HIT_VERIFIED';
const mappedProgress=jobProgressCopy(currentProgress,latestEvent?.phase);
const progressLabel=cachedFiles&&mappedProgress==='Downloading'?'Verifying':mappedProgress;
const cacheCopy=materializationCopy(cacheStatus);
const fullJourney=lastWasFull||jobEvents.some(event=>['download','materialization','verif'].some(token=>event.phase.toLowerCase().includes(token)));
const journeySteps=fullJourney?(cachedFiles?['Waiting','Verifying','Preparing','Ready']:['Waiting','Downloading','Verifying','Preparing','Ready']):['Waiting','Preparing','Ready'];
const retryPreparation=()=>{if(jobId&&!jobResult){setJobError(null);setSubscriptionKey(value=>value+1);return}setJobId(null);setJobResult(null);if(lastWasFull){setConsent(true);setConsentOpen(true)}else void startPreparation(false)};
return <div className="page-fade min-h-full model-workspace page-shell">
  <header className="models-header"><div><div className="eyebrow">Model library</div><h1>Models</h1><p>Paste a public Hugging Face model ID to inspect its metadata. Inspection does not download model files.</p></div><form onSubmit={inspect} className="models-search"><Search size={17}/><input aria-label="Public Hugging Face model ID" value={modelId} onChange={e=>updateModel(e.target.value)} placeholder="Paste a public Hugging Face model ID"/><button disabled={loading||!modelId.trim()}>{loading?'Inspecting…':'Inspect'} <ArrowRight size={15}/></button></form></header>
  <div className="model-content">
  {error&&<section className="focus-panel mb-8 p-6 md:p-8 flex flex-col md:flex-row md:items-center justify-between gap-6"><div className="flex gap-4"><div className="w-11 h-11 rounded-xl bg-red-500/10 text-red-400 flex items-center justify-center shrink-0"><AlertTriangle size={20}/></div><div><h2 className="text-lg font-semibold">We couldn’t inspect this model</h2><p className="text-sm text-zinc-500 mt-1 max-w-2xl leading-relaxed">{error}</p><p className="text-xs text-zinc-600 mt-3">Check that the repository is public and the model ID and revision are correct.</p></div></div><button onClick={()=>inspect()} className="btn-secondary shrink-0"><RotateCcw size={14}/>Retry inspection</button></section>}
  {!metadata&&!loading&&<section><div className="flex flex-col sm:flex-row sm:justify-between sm:items-end gap-4 mb-5"><div><div className="eyebrow mb-2">Start with a model</div><h2 className="text-xl font-semibold">Suggested model IDs</h2><p className="text-sm text-zinc-500 mt-1">Select one, then choose Inspect to load its real repository metadata.</p></div><details className="text-xs text-zinc-600"><summary className="cursor-pointer">Advanced options</summary><label className="mt-3 flex items-center gap-2">Revision <input aria-label="Advanced revision" value={revision} onChange={e=>{setRevision(e.target.value);setMetadata(null);setError(null)}} className="w-28 bg-transparent border-b hairline py-1 text-zinc-300 font-mono outline-none"/></label></details></div><div className="grid md:grid-cols-3 gap-3">{PRESETS.map((p,i)=><button key={p.id} onClick={()=>{updateModel(p.id);setRevision('main')}} className="card-interactive p-5 md:p-6 text-left"><div className="flex justify-between"><span className="model-card-index">0{i+1}</span><Box size={17} className="text-zinc-600"/></div><div className="mt-7 text-lg font-semibold tracking-[-.025em]">{p.name} <span className="text-zinc-500">{p.size}</span></div><div className="text-sm text-zinc-500 mt-2">{p.note}</div><div className="mt-6 pt-4 border-t hairline text-xs text-red-300 flex items-center justify-between">Select this model <ArrowRight size={13}/></div></button>)}</div></section>}
  {loading&&<section aria-label="Inspecting model" className="grid md:grid-cols-[1.4fr_.8fr] gap-4"><div className="focus-panel p-7 md:p-9"><div className="flex items-center gap-3 text-sm text-zinc-400"><span className="w-2 h-2 rounded-full bg-red-500 animate-pulse"/>Resolving model identity and architecture</div><div className="h-8 w-2/3 rounded-lg shimmer mt-8"/><div className="h-4 w-1/3 rounded shimmer mt-3"/><div className="grid grid-cols-2 lg:grid-cols-4 gap-2 mt-10">{[0,1,2,3].map(i=><div key={i} className="h-20 rounded-xl shimmer"/>)}</div></div><div className="focus-panel p-7"><div className="h-3 w-1/2 rounded shimmer"/><div className="h-16 rounded-xl shimmer mt-8"/><div className="h-28 rounded-xl shimmer mt-4"/></div></section>}
  {metadata&&<nav aria-label="Model workspace" className="model-workspace-tabs">{(['overview','runs','files','compatibility'] as const).map(tab=><button key={tab} aria-current={workspaceTab===tab?'page':undefined} onClick={()=>setWorkspaceTab(tab)}>{tab[0].toUpperCase()+tab.slice(1)}</button>)}</nav>}
  {metadata&&workspaceTab==='runs'&&<section className="workspace-pane"><div><span className="eyebrow">Model activity</span><h2>{metadata.model_id}</h2></div>{jobId?<div className="model-run-row"><span>{jobResult?.domain_status?DOMAIN_STATUS_COPY[jobResult.domain_status].label:'Preparation in progress'}</span><code>{jobId}</code></div>:<p>No runs for this model in this workspace session yet.</p>}<button className="text-action" onClick={()=>onNavigate('runs')}>Open all activity <ArrowRight size={14}/></button></section>}
  {metadata&&workspaceTab==='files'&&<section className="workspace-pane"><span className="eyebrow">Model files</span><h2>Repository contents</h2><p>{metadata.files_count} files reported by inspection. This check reads repository metadata only; it does not download model weights.</p>{jobResult?.domain_status==='PREPARED'?<div className="model-run-row"><strong>Verified model files are available on connected compute</strong><span>Files remain on that compute device · not stored by ROCmHub</span></div>:<div className="model-run-row">Model weights have not been prepared for this workspace.</div>}<details className="technical-details"><summary>Technical details</summary><p>Format: {metadata.weights_format||'Not reported'} · Resolved revision: <code>{metadata.commit_sha}</code></p></details></section>}
  {metadata&&workspaceTab==='compatibility'&&<section className="workspace-pane"><span className="eyebrow">Compatibility</span><h2>{jobResult?.domain_status==='EXECUTED'?'AMD execution evidence':'Not tested on AMD hardware yet.'}</h2><p>Model metadata can be inspected without compute. Compatibility notes are not a certification or evidence of execution.</p>{metadata.compatibility.reasons.concat(metadata.compatibility.warnings.map(message=>({code:'warning',message,severity:'warning'}))).length>0&&<ul className="compatibility-list">{metadata.compatibility.reasons.concat(metadata.compatibility.warnings.map(message=>({code:'warning',message,severity:'warning'}))).map((item,i)=><li key={i}>{item.message}</li>)}</ul>}</section>}
  {metadata&&workspaceTab==='overview'&&<section className="grid xl:grid-cols-[1.45fr_.75fr] gap-4 items-stretch">
    <div className="focus-panel p-7 md:p-9"><div className="flex flex-col md:flex-row md:items-start justify-between gap-6"><div className="min-w-0"><div className="text-xs text-zinc-500">Model profile</div><h2 className="text-2xl md:text-3xl font-semibold tracking-[-.04em] mt-2 break-words">{metadata.model_id}</h2><p className="text-sm text-zinc-500 mt-2">{metadata.pipeline_tag||'Text generation'} · {metadata.license||'License not declared'}</p></div><div className="w-12 h-12 rounded-xl bg-red-500/10 flex items-center justify-center text-red-400 shrink-0"><Layers size={22}/></div></div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-px bg-white/[.08] rounded-2xl overflow-hidden mt-8"><Metric label="Architecture" value={metadata.architecture||'Unknown'}/><Metric label="Parameters" value={metadata.parameter_count?`${(metadata.parameter_count/1e9).toFixed(2)}B`:'Unknown'}/><Metric label="Context" value={metadata.context_length?metadata.context_length.toLocaleString():'Unknown'}/><Metric label="Format" value={metadata.weights_format||'Safetensors'}/></div>
      <details className="mt-5 border-t hairline pt-4"><summary className="flex items-center gap-2 text-sm text-content-secondary cursor-pointer">AMD execution environment <span className="environment-state">{metadata.host_gpus_detected > 0 ? 'Detected on this host' : 'Not detected on this host'}</span><ChevronDown size={14}/></summary><div className="mt-3"><div className="section-label mb-3">Technical environment</div>{metadata.compatibility.reasons.length>0||metadata.compatibility.warnings.length>0?<ul className="space-y-2">{[...metadata.compatibility.reasons,...metadata.compatibility.warnings.map(message=>({message,severity:'warning'}))].slice(0,4).map((item,index)=><li key={`${item.message}-${index}`} className="flex items-start gap-2 text-sm leading-relaxed text-zinc-400"><span className={`mt-2 w-1.5 h-1.5 rounded-full shrink-0 ${item.severity==='critical'?'bg-red-400':item.severity==='warning'?'bg-amber-400':'bg-zinc-500'}`}/>{item.message}</li>)}</ul>:<p className="text-sm text-zinc-500">No compatibility notes were returned. Inspection does not certify AMD execution.</p>}<p className="text-sm text-zinc-500 mt-3">GPU · ROCm · HIP · PyTorch details are available in technical inspection data. Connected compute appears in the header.</p></div></details>
      <details className="mt-6 border-t hairline pt-5"><summary className="flex items-center gap-2 text-xs text-zinc-500 cursor-pointer">Technical details <ChevronDown size={13}/></summary><div className="mt-4 grid sm:grid-cols-2 gap-3 text-xs"><Detail label="Resolved revision" value={metadata.commit_sha}/><Detail label="Repository files" value={`${metadata.files_count}`}/><Detail label="Host accelerators" value={`${metadata.host_gpus_detected}`}/><Detail label="Requested revision" value={metadata.requested_revision}/></div></details>
    </div>
    <aside className="focus-panel p-6 md:p-7 flex flex-col"><div className="eyebrow">Next step</div><div className="mt-5 flex items-start gap-4"><CheckCircle2 size={25} className="text-content-muted shrink-0"/><div><h3 className="text-xl font-semibold">Prepare this model</h3><p className="text-sm text-zinc-400 leading-relaxed mt-2">Preparation creates a setup; it does not run the model. Running it requires compatible AMD compute and a separate run action.</p></div></div><div className="mt-6 space-y-2"><div className="prep-choice"><div><div className="text-sm font-medium">Prepare configuration only</div><p className="text-sm text-zinc-500 mt-1">Creates reproducible setup files. No model weights are downloaded.</p></div><span className="prep-choice-tag">No download</span></div><div className="prep-choice"><div><div className="text-sm font-medium">Download &amp; prepare model files</div><p className="text-sm text-zinc-500 mt-1">With your consent, downloads the real files to connected compute. No inference is run.</p></div><span className="prep-choice-tag prep-choice-tag-red">Consent required</span></div></div><div className="mt-auto pt-5 space-y-2"><button onClick={()=>startPreparation(false)} disabled={preparing} className="btn-secondary w-full">{preparing?'Queueing…':'Prepare configuration only'} <ArrowRight size={15}/></button><button onClick={()=>{setConsent(false);setConsentOpen(true)}} disabled={preparing} className="btn-primary w-full"><Download size={15}/>Download &amp; Prepare</button><button onClick={()=>onSelectModelForForge(metadata.model_id,metadata.commit_sha)} className="btn-ghost w-full">Advanced build options</button></div></aside>
  </section>}
  {consentOpen&&metadata&&<section role="dialog" aria-modal="true" aria-labelledby="download-consent-title" className="focus-panel mt-6 p-6 md:p-8 border border-red-500/20"><div className="flex items-start gap-4"><div className="w-10 h-10 rounded-xl bg-red-500/10 text-red-400 flex items-center justify-center shrink-0"><Download size={19}/></div><div className="min-w-0 flex-1"><h2 id="download-consent-title" className="text-xl font-semibold">Download real model files?</h2><p className="text-sm text-zinc-400 mt-2">This downloads model weights and tokenizer files for preparation.</p><dl className="grid sm:grid-cols-2 gap-3 mt-5 text-xs"><Detail label="Model" value={metadata.model_id}/><Detail label="Resolved model version" value={metadata.commit_sha}/><Detail label="Requested build target (not detected hardware)" value="Radeon RX 7900 XTX"/><Detail label="Estimated storage" value={estimateBytes?`~${(estimateBytes/1024**3).toFixed(1)} GB · estimate`:'Estimate unavailable'}/></dl><p className="text-xs text-zinc-500 mt-4">Files are stored on connected compute, not in ROCmHub. If no compatible compute is connected, the request waits. Downloading does not run inference or validate AMD hardware.</p><label className="mt-5 flex items-start gap-3 p-4 rounded-xl bg-white/[.03] text-sm text-zinc-300"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1 accent-red-500"/><span>I explicitly consent to downloading these model files to connected compute.</span></label><div className="flex flex-col-reverse sm:flex-row justify-end gap-2 mt-5"><button className="btn-ghost" onClick={()=>setConsentOpen(false)}>Cancel</button><button className="btn-primary" disabled={!consent||preparing} onClick={()=>{setConsentOpen(false);void startPreparation(true)}}>{preparing?'Queueing…':'Confirm · Download & Prepare'} <ArrowRight size={14}/></button></div></div></div></section>}
  {jobId&&<section aria-live="polite" className="focus-panel mt-6 p-6 md:p-8">
    <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
      <div>
        <div className="eyebrow">Preparation progress</div>
        <h2 className="text-xl font-semibold mt-2">{jobResult?.domain_status?DOMAIN_STATUS_COPY[jobResult.domain_status].label:jobResult?.job_status==='FAILED'?'Preparation failed':jobResult?.job_status==='CANCELLED'?'Preparation cancelled':progressLabel==='Waiting'?'Waiting for compute':currentProgress==='SUCCEEDED'?'Checking preparation result':'Preparing your model'}</h2>
        <p className="text-sm text-zinc-500 mt-2">{jobResult?.domain_status?DOMAIN_STATUS_COPY[jobResult.domain_status].explanation:currentProgress==='SUCCEEDED'?'The request finished. Loading its recorded outcome; preparation is not confirmed until the result is available.':progressLabel==='Waiting'?'This preparation will start automatically when compatible compute is available.':`${progressLabel} your model setup. We do not estimate a completion percentage.`}</p>
        <details className="mt-3"><summary className="text-sm text-zinc-600 cursor-pointer">Technical details</summary><p className="text-sm text-zinc-600 mt-2 font-mono break-all">Run ID: {jobId}{jobResult?.domain_status?` · ${jobResult.domain_status}`:''}</p>{jobEvents.length>0&&<div className="mt-2 space-y-2">{jobEvents.slice(-5).map((event,index)=><p key={`${event.event_id}-${index}`} className="text-sm text-zinc-500 break-words">{event.phase} · {event.message}</p>)}</div>}</details>
      </div>
      {!jobResult&&!['SUCCEEDED','FAILED','CANCELLED'].includes(currentProgress)&&<button className="btn-ghost" onClick={()=>cancelJob(jobId).then(()=>toast.success('Cancellation requested')).catch(e=>toast.error(e.message))}><Square size={15}/>Cancel</button>}
    </div>
    {!jobResult&&!['SUCCEEDED','FAILED','CANCELLED'].includes(currentProgress)&&<ol className={`journey-steps ${fullJourney?'journey-steps-full':''}`}>{journeySteps.map((label,index)=>{const current=progressLabel===label;const done=journeySteps.indexOf(progressLabel)>index;return <li key={label} className={`${current?'journey-step-current':''} ${done?'journey-step-done':''}`} aria-current={current?'step':undefined}><span>{done&&!current?'✓':`0${index+1}`}</span><strong>{label}</strong></li>})}</ol>}
    {jobError&&<div className="mt-5 p-4 rounded-xl bg-red-500/[.06] text-sm text-red-300 flex items-center justify-between gap-3"><span>{jobError}</span><button className="btn-ghost shrink-0" onClick={retryPreparation}><RotateCcw size={15}/>Retry</button></div>}
    {jobResult?.domain_status==='PREPARED'&&<div className="mt-6 grid sm:grid-cols-3 gap-2"><div className="p-4 rounded-xl bg-white/[.025] text-sm"><ShieldCheck size={17} className="text-content-muted"/><div className="mt-2 font-semibold">{cacheCopy.title}</div><p className="text-sm text-zinc-500 mt-1">{cacheCopy.description}</p>{cacheStatus&&<details className="technical-details"><summary>Technical materialization details</summary><p>{cacheStatus}{jobResult.result?.materialization?.integrity?` · ${jobResult.result.materialization.integrity}`:''}</p></details>}</div><div className="p-4 rounded-xl bg-white/[.025] text-sm"><div className="text-zinc-500">Resolved model version</div><div className="font-mono text-sm text-zinc-300 mt-2 break-all">{metadata?.commit_sha}</div><details className="technical-details"><summary>Technical details</summary><p>Immutable revision recorded with this preparation.</p></details></div><div className="p-4 rounded-xl bg-white/[.025] text-sm"><div className="text-zinc-500">Model execution</div><div className="text-sm text-zinc-300 mt-2">Not performed</div></div></div>}
  </section>}
  {jobResult?.domain_status==='CONFIG_ONLY'&&<section className="focus-panel mt-6 p-6 md:p-8"><div className="eyebrow">Preparation result</div><h2 className="text-xl font-semibold mt-2">{DOMAIN_STATUS_COPY.CONFIG_ONLY.label}</h2><p className="text-sm text-zinc-400 mt-2">Configuration and launcher files are ready. Model weights were not downloaded.</p><p className="text-xs text-zinc-500 mt-3">AMD execution was not performed · AMD validation was not performed</p><details className="mt-4"><summary className="text-xs text-zinc-600 cursor-pointer">Technical details</summary><p className="text-xs font-mono text-zinc-600 mt-2">CONFIG_ONLY</p></details></section>}
  {jobResult?.job_status==='CANCELLED'&&<section className="focus-panel mt-6 p-6 border border-amber-500/20"><h2 className="font-semibold">Cancelled safely</h2><p className="text-sm text-zinc-500 mt-2">This job did not publish a complete cache entry. You can retry when ready.</p><button className="btn-ghost mt-4" onClick={retryPreparation}><RotateCcw size={13}/>Retry materialization</button></section>}
  </div>
</div>};
const Metric=({label,value}:{label:string;value:string})=><div className="surface-secondary p-5 min-w-0"><div className="text-[10px] uppercase tracking-widest text-zinc-600">{label}</div><div className="mt-2 text-sm font-semibold truncate" title={value}>{value}</div></div>;
const Detail=({label,value}:{label:string;value:string})=><div className="flex gap-3 justify-between p-3 bg-white/[.025] rounded-lg"><span className="text-zinc-600">{label}</span><span className="font-mono text-zinc-400 truncate max-w-[60%]">{value}</span></div>;
