import React,{useState} from 'react';
import type {ModelMetadata} from '../../api/types';
import {fetchModel,ApiError} from '../../api/client';
import {Search,ArrowRight,Layers,Box,CheckCircle2,AlertTriangle,ChevronDown,RotateCcw} from 'lucide-react';
import type {NavTab} from '../layout/Sidebar';
import {useToast} from '../common/Toast';
import modelExplorerHeroImg from '../../assets/visuals/model_explorer_hero.jpg';
interface Props{onSelectModelForForge:(modelId:string,revision?:string)=>void;onNavigate:(tab:NavTab)=>void}
const PRESETS=[{id:'Qwen/Qwen2.5-0.5B-Instruct',name:'Qwen 2.5',size:'0.5B',note:'Fast first build'},{id:'Qwen/Qwen2.5-1.5B-Instruct',name:'Qwen 2.5',size:'1.5B',note:'Balanced assistant'},{id:'Qwen/Qwen2.5-7B-Instruct',name:'Qwen 2.5',size:'7B',note:'Production class'}];
export const ModelExplorerView:React.FC<Props>=({onSelectModelForForge})=>{const toast=useToast();const[modelId,setModelId]=useState(PRESETS[0].id);const[revision,setRevision]=useState('main');const[metadata,setMetadata]=useState<ModelMetadata|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);
const updateModel=(value:string)=>{setModelId(value);setMetadata(null);setError(null)};
const inspect=async(e?:React.FormEvent)=>{e?.preventDefault();if(!modelId.trim())return;setLoading(true);setError(null);try{setMetadata(await fetchModel(modelId.trim(),revision.trim()||'main'));toast.success('Model inspection complete')}catch(err:any){const msg=err instanceof ApiError?err.message:err.message||'Unable to inspect model';setError(msg);setMetadata(null);toast.error(msg)}finally{setLoading(false)}};
return <div className="page-fade min-h-full">
  <section className="relative overflow-hidden border-b hairline"><img src={modelExplorerHeroImg} alt="Model topology" className="hero-image absolute inset-y-0 right-0 w-[58%] h-full object-cover opacity-45"/><div className="absolute inset-0 bg-gradient-to-r from-[#09090b] via-[#09090b]/95 to-transparent"/><div className="relative page-shell py-16 md:py-20"><div className="max-w-3xl"><div className="eyebrow mb-5">Model discovery</div><h1 className="page-title">Find the right model.<br/><span className="text-zinc-500">Know what comes next.</span></h1><p className="lede mt-6 max-w-xl">Inspect any public Hugging Face model and turn its architecture into an actionable AMD preparation path.</p><form onSubmit={inspect} className="mt-9 flex flex-col sm:flex-row gap-3 max-w-2xl"><label className="relative flex-1"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500"/><input aria-label="Model ID" value={modelId} onChange={e=>updateModel(e.target.value)} className="input-field !pl-12 !h-14 !text-base" placeholder="Search by model ID"/></label><button disabled={loading||!modelId.trim()} className="btn-primary !h-14 px-6">{loading?<><span className="w-4 h-4 rounded-full border-2 border-white/30 border-t-white animate-spin"/>Inspecting</>:<>Inspect model <ArrowRight size={16}/></>}</button></form></div></div></section>
  <div className="page-shell py-10">
  {error&&<section className="focus-panel mb-8 p-6 md:p-8 flex flex-col md:flex-row md:items-center justify-between gap-6"><div className="flex gap-4"><div className="w-11 h-11 rounded-xl bg-red-500/10 text-red-400 flex items-center justify-center shrink-0"><AlertTriangle size={20}/></div><div><h2 className="text-lg font-semibold">We couldn’t inspect this model</h2><p className="text-sm text-zinc-500 mt-1 max-w-2xl leading-relaxed">{error}</p><p className="text-xs text-zinc-600 mt-3">Check that the repository is public and the model ID and revision are correct.</p></div></div><button onClick={()=>inspect()} className="btn-secondary shrink-0"><RotateCcw size={14}/>Retry inspection</button></section>}
  {!metadata&&!loading&&<section><div className="flex flex-col sm:flex-row sm:justify-between sm:items-end gap-4 mb-5"><div><h2 className="text-xl font-semibold">{error?'Try a known model':'Curated starting points'}</h2><p className="text-sm text-zinc-600 mt-1">Popular sizes for learning the workflow.</p></div><label className="text-xs text-zinc-600">Revision <input value={revision} onChange={e=>{setRevision(e.target.value);setMetadata(null);setError(null)}} className="ml-2 w-24 bg-transparent border-b hairline py-1 text-zinc-300 font-mono outline-none"/></label></div><div className="grid md:grid-cols-3 gap-3">{PRESETS.map((p,i)=><button key={p.id} onClick={()=>{updateModel(p.id);setRevision('main')}} className="card-interactive p-6 text-left"><div className="flex justify-between"><span className="text-[10px] text-zinc-600 font-mono">0{i+1}</span><Box size={18} className="text-zinc-600"/></div><div className="mt-8 text-xl font-semibold">{p.name} <span className="text-zinc-500">{p.size}</span></div><div className="text-sm text-zinc-500 mt-2">{p.note}</div><div className="mt-7 text-xs text-red-400 flex items-center gap-2">Select model <ArrowRight size={13}/></div></button>)}</div></section>}
  {loading&&<section aria-label="Inspecting model" className="grid md:grid-cols-[1.4fr_.8fr] gap-4"><div className="focus-panel p-7 md:p-9"><div className="flex items-center gap-3 text-sm text-zinc-400"><span className="w-2 h-2 rounded-full bg-red-500 animate-pulse"/>Resolving model identity and architecture</div><div className="h-8 w-2/3 rounded-lg shimmer mt-8"/><div className="h-4 w-1/3 rounded shimmer mt-3"/><div className="grid grid-cols-2 lg:grid-cols-4 gap-2 mt-10">{[0,1,2,3].map(i=><div key={i} className="h-20 rounded-xl shimmer"/>)}</div></div><div className="focus-panel p-7"><div className="h-3 w-1/2 rounded shimmer"/><div className="h-16 rounded-xl shimmer mt-8"/><div className="h-28 rounded-xl shimmer mt-4"/></div></section>}
  {metadata&&<section className="grid xl:grid-cols-[1.45fr_.75fr] gap-4 items-stretch">
    <div className="focus-panel p-7 md:p-9"><div className="flex flex-col md:flex-row md:items-start justify-between gap-6"><div className="min-w-0"><div className="text-xs text-zinc-500">Model profile</div><h2 className="text-2xl md:text-3xl font-semibold tracking-[-.04em] mt-2 break-words">{metadata.model_id}</h2><p className="text-sm text-zinc-500 mt-2">{metadata.pipeline_tag||'Text generation'} · {metadata.license||'License not declared'}</p></div><div className="w-12 h-12 rounded-xl bg-red-500/10 flex items-center justify-center text-red-400 shrink-0"><Layers size={22}/></div></div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-px bg-white/[.08] rounded-2xl overflow-hidden mt-10"><Metric label="Architecture" value={metadata.architecture||'Unknown'}/><Metric label="Parameters" value={metadata.parameter_count?`${(metadata.parameter_count/1e9).toFixed(2)}B`:'Unknown'}/><Metric label="Context" value={metadata.context_length?metadata.context_length.toLocaleString():'Unknown'}/><Metric label="Format" value={metadata.weights_format||'Safetensors'}/></div>
      <details className="mt-6 border-t hairline pt-5"><summary className="flex items-center gap-2 text-xs text-zinc-500 cursor-pointer">Technical details <ChevronDown size={13}/></summary><div className="mt-4 grid sm:grid-cols-2 gap-3 text-xs"><Detail label="Resolved revision" value={metadata.commit_sha}/><Detail label="Repository files" value={`${metadata.files_count}`}/><Detail label="Host accelerators" value={`${metadata.host_gpus_detected}`}/><Detail label="Requested revision" value={metadata.requested_revision}/></div></details>
    </div>
    <aside className="focus-panel p-7 md:p-8 flex flex-col"><div className="eyebrow">Preparation readiness</div><div className="mt-8 flex items-start gap-4">{metadata.compatibility.verdict==='READY'?<CheckCircle2 size={28} className="text-emerald-400 shrink-0"/>:<AlertTriangle size={28} className="text-amber-400 shrink-0"/>}<div><h3 className="text-xl font-semibold">{metadata.compatibility.verdict==='READY'?'Ready to prepare':'Preparation path available'}</h3><p className="text-sm text-zinc-500 leading-relaxed mt-2">{metadata.rocm_available?'This host can continue into accelerated validation.':'Build configuration is available here. Run hardware validation later on a ROCm host.'}</p></div></div><div className="mt-8 pt-6 border-t hairline"><div className="text-xs text-zinc-600">Recommended next step</div><p className="text-sm mt-2">Create a reproducible FP16 plan for an AMD target.</p></div><button onClick={()=>onSelectModelForForge(metadata.model_id,metadata.commit_sha)} className="btn-primary mt-auto w-full">Continue to Forge <ArrowRight size={15}/></button></aside>
  </section>}
  </div>
</div>};
const Metric=({label,value}:{label:string;value:string})=><div className="bg-[#101012] p-5 min-w-0"><div className="text-[10px] uppercase tracking-widest text-zinc-600">{label}</div><div className="mt-2 text-sm font-semibold truncate" title={value}>{value}</div></div>;
const Detail=({label,value}:{label:string;value:string})=><div className="flex gap-3 justify-between p-3 bg-white/[.025] rounded-lg"><span className="text-zinc-600">{label}</span><span className="font-mono text-zinc-400 truncate max-w-[60%]">{value}</span></div>;
