"""Core domain models and exceptions for ROCmHub."""

from rocmhub.core.errors import (
    ArtifactPackagingError,
    AuthRequiredError,
    BenchmarkError,
    ConfigurationError,
    HardwareDetectionError,
    InvalidModelMetadataError,
    ModelInspectionError,
    ModelNotFoundError,
    ModelResolutionError,
    NetworkError,
    NotImplementedFeatureError,
    RemoteCodeRequiredError,
    RevisionNotFoundError,
    ROCmHubError,
    RunnerExecutionError,
    SchemaValidationError,
)
from rocmhub.core.types import (
    ArtifactManifest,
    BenchmarkResult,
    DetectionReport,
    EnvironmentSpec,
    ExecutionStatus,
    ExperimentSpec,
    HardwareSpec,
    ModelSpec,
)

__all__ = [
    "ROCmHubError",
    "ConfigurationError",
    "SchemaValidationError",
    "HardwareDetectionError",
    "ModelResolutionError",
    "ModelNotFoundError",
    "AuthRequiredError",
    "RevisionNotFoundError",
    "NetworkError",
    "ModelInspectionError",
    "InvalidModelMetadataError",
    "RemoteCodeRequiredError",
    "RunnerExecutionError",
    "BenchmarkError",
    "ArtifactPackagingError",
    "NotImplementedFeatureError",
    "ExecutionStatus",
    "ModelSpec",
    "HardwareSpec",
    "EnvironmentSpec",
    "DetectionReport",
    "ExperimentSpec",
    "BenchmarkResult",
    "ArtifactManifest",
]
