"""ROCmHub: Automated AI model preparation, optimization, and benchmarking for AMD GPUs and ROCm."""

from __future__ import annotations

__version__ = "0.1.0"

from rocmhub.artifacts import ArtifactBuilder, LocalArtifactStore
from rocmhub.benchmarks import (
    BenchmarkConfig,
    BenchmarkHarness,
    BenchmarkRunMeasurement,
    MetricsCalculator,
)
from rocmhub.capabilities import CapabilityEvaluator, CapabilityPolicy
from rocmhub.core.errors import ROCmHubError
from rocmhub.core.types import (
    ArtifactFileEntry,
    ArtifactManifest,
    ArtifactStatus,
    ArtifactVerificationResult,
    BenchmarkResult,
    CapabilityReport,
    DetectionReport,
    DeviceCapabilityAssessment,
    EnvironmentFingerprint,
    EnvironmentSpec,
    EvaluationReason,
    EvaluationSeverity,
    EvaluationVerdict,
    ExecutionStatus,
    ExperimentRole,
    ExperimentSpec,
    GuardPolicy,
    GuardVerdict,
    HardwareHealthSnapshot,
    HardwareSpec,
    ModelSpec,
    ReferenceComparison,
    ReferenceMeasurement,
    ReproducibilityReport,
    ReproductionMetadata,
    RunResult,
    SystemCapabilities,
    ValidationCase,
    ValidationMode,
    ValidationReport,
    ValidationRunResult,
    ValidationVerdict,
)
from rocmhub.engineer import (
    AIEngineer,
    EngineerBudget,
    EngineerObjective,
    EngineerReport,
    EngineerRequest,
    EngineerStatus,
)
from rocmhub.forge import (
    BuildManifest,
    BuildStatus,
    BuildStepRecord,
    BuildStepSpec,
    ForgeExecutor,
    ForgePlan,
    ForgePlanner,
    ForgeRecipe,
    MaterializedModel,
    ModelMaterializer,
    PyTorchTransformersHipRecipe,
    StepStatus,
)
from rocmhub.guard import (
    DEFAULT_GUARD_POLICY,
    ABBASequence,
    BenchmarkGuard,
)
from rocmhub.optimization import (
    CandidateStatus,
    ComparisonEngine,
    ComparisonResult,
    ComparisonVerdict,
    OptimizationBaseline,
    OptimizationCandidate,
    OptimizationExecutor,
    OptimizationPlan,
    OptimizationRecipe,
    OptimizationReport,
    OptimizationRequest,
    OptimizationStrategy,
)
from rocmhub.runners import BaseRunner, HuggingFaceRunner
from rocmhub.server import JobManager, ServerConfig, create_app
from rocmhub.validation import ValidationConfig, ValidationEvaluator

__all__ = [
    "__version__",
    "ROCmHubError",
    "CapabilityEvaluator",
    "CapabilityPolicy",
    "BaseRunner",
    "HuggingFaceRunner",
    "BenchmarkConfig",
    "BenchmarkRunMeasurement",
    "BenchmarkHarness",
    "MetricsCalculator",
    "ExecutionStatus",
    "ModelSpec",
    "HardwareSpec",
    "EnvironmentSpec",
    "DetectionReport",
    "CapabilityReport",
    "DeviceCapabilityAssessment",
    "EvaluationReason",
    "EvaluationSeverity",
    "EvaluationVerdict",
    "SystemCapabilities",
    "RunResult",
    "ExperimentSpec",
    "BenchmarkResult",
    "ValidationConfig",
    "ValidationEvaluator",
    "ValidationReport",
    "ValidationVerdict",
    "ValidationMode",
    "ValidationCase",
    "ValidationRunResult",
    "ArtifactStatus",
    "ArtifactFileEntry",
    "ReproductionMetadata",
    "ArtifactVerificationResult",
    "ArtifactManifest",
    "ArtifactBuilder",
    "LocalArtifactStore",
    "GuardVerdict",
    "ExperimentRole",
    "HardwareHealthSnapshot",
    "GuardPolicy",
    "EnvironmentFingerprint",
    "ReferenceMeasurement",
    "ReferenceComparison",
    "ReproducibilityReport",
    "BenchmarkGuard",
    "ABBASequence",
    "DEFAULT_GUARD_POLICY",
    "BuildStatus",
    "StepStatus",
    "BuildStepSpec",
    "BuildStepRecord",
    "MaterializedModel",
    "ForgePlan",
    "ForgeRecipe",
    "PyTorchTransformersHipRecipe",
    "ForgePlanner",
    "ModelMaterializer",
    "BuildManifest",
    "ForgeExecutor",
    "AIEngineer",
    "EngineerObjective",
    "EngineerStatus",
    "EngineerBudget",
    "EngineerRequest",
    "EngineerReport",
    "CandidateStatus",
    "ComparisonResult",
    "ComparisonVerdict",
    "OptimizationBaseline",
    "OptimizationCandidate",
    "OptimizationPlan",
    "OptimizationReport",
    "OptimizationRequest",
    "OptimizationStrategy",
    "ComparisonEngine",
    "OptimizationExecutor",
    "OptimizationRecipe",
    "create_app",
    "ServerConfig",
    "JobManager",
]
